// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	GateRequest
	CenterRequest
	CenterResponse
	GateInfo
	HelloRequest
	HelloResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GateState int32

const (
	GateState_Online  GateState = 0
	GateState_Offline GateState = 1
	GateState_Close   GateState = 2
)

var GateState_name = map[int32]string{
	0: "Online",
	1: "Offline",
	2: "Close",
}
var GateState_value = map[string]int32{
	"Online":  0,
	"Offline": 1,
	"Close":   2,
}

func (x GateState) String() string {
	return proto.EnumName(GateState_name, int32(x))
}
func (GateState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// gate服务 登录认证 协议号3  重连 5
type GateRequest struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	Uid    uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	ChanId string `protobuf:"bytes,3,opt,name=chanId" json:"chanId,omitempty"`
}

func (m *GateRequest) Reset()                    { *m = GateRequest{} }
func (m *GateRequest) String() string            { return proto.CompactTextString(m) }
func (*GateRequest) ProtoMessage()               {}
func (*GateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GateRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GateRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GateRequest) GetChanId() string {
	if m != nil {
		return m.ChanId
	}
	return ""
}

// center服务 rpc接口
type CenterRequest struct {
	Uid  []uint64  `protobuf:"varint,1,rep,packed,name=uid" json:"uid,omitempty"`
	Gate *GateInfo `protobuf:"bytes,2,opt,name=gate" json:"gate,omitempty"`
}

func (m *CenterRequest) Reset()                    { *m = CenterRequest{} }
func (m *CenterRequest) String() string            { return proto.CompactTextString(m) }
func (*CenterRequest) ProtoMessage()               {}
func (*CenterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CenterRequest) GetUid() []uint64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *CenterRequest) GetGate() *GateInfo {
	if m != nil {
		return m.Gate
	}
	return nil
}

type CenterResponse struct {
	Online []bool `protobuf:"varint,1,rep,packed,name=online" json:"online,omitempty"`
}

func (m *CenterResponse) Reset()                    { *m = CenterResponse{} }
func (m *CenterResponse) String() string            { return proto.CompactTextString(m) }
func (*CenterResponse) ProtoMessage()               {}
func (*CenterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CenterResponse) GetOnline() []bool {
	if m != nil {
		return m.Online
	}
	return nil
}

// 网关信息
type GateInfo struct {
	Addr   string    `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Weight int32     `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
	State  GateState `protobuf:"varint,3,opt,name=state,enum=pb.GateState" json:"state,omitempty"`
	Name   string    `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *GateInfo) Reset()                    { *m = GateInfo{} }
func (m *GateInfo) String() string            { return proto.CompactTextString(m) }
func (*GateInfo) ProtoMessage()               {}
func (*GateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GateInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *GateInfo) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *GateInfo) GetState() GateState {
	if m != nil {
		return m.State
	}
	return GateState_Online
}

func (m *GateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 测试接口请求 1001
type HelloRequest struct {
	ReqMsg string `protobuf:"bytes,1,opt,name=req_msg,json=reqMsg" json:"req_msg,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HelloRequest) GetReqMsg() string {
	if m != nil {
		return m.ReqMsg
	}
	return ""
}

// 测试接口返回 1002
type HelloResponse struct {
	RespMsg string `protobuf:"bytes,1,opt,name=resp_msg,json=respMsg" json:"resp_msg,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HelloResponse) GetRespMsg() string {
	if m != nil {
		return m.RespMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GateRequest)(nil), "pb.GateRequest")
	proto.RegisterType((*CenterRequest)(nil), "pb.CenterRequest")
	proto.RegisterType((*CenterResponse)(nil), "pb.CenterResponse")
	proto.RegisterType((*GateInfo)(nil), "pb.GateInfo")
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "pb.HelloResponse")
	proto.RegisterEnum("pb.GateState", GateState_name, GateState_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xcb, 0x6e, 0x83, 0x30,
	0x10, 0x2c, 0x09, 0x79, 0x6d, 0x1e, 0x8a, 0x7c, 0x68, 0xe9, 0x0d, 0xb9, 0x87, 0x46, 0x39, 0xa4,
	0x52, 0xfa, 0x09, 0x1c, 0xda, 0x1c, 0x22, 0x24, 0xf7, 0x03, 0x2a, 0x1e, 0x0b, 0x41, 0x02, 0x1b,
	0x6c, 0x47, 0xfd, 0xfd, 0xca, 0xc6, 0xae, 0x7a, 0xdb, 0x61, 0x67, 0x66, 0x67, 0x30, 0x6c, 0x0a,
	0xd1, 0x75, 0x82, 0x9f, 0x7a, 0x29, 0xb4, 0x20, 0x93, 0x3e, 0xa7, 0x29, 0xac, 0x3f, 0x32, 0x8d,
	0x0c, 0x87, 0x3b, 0x2a, 0x4d, 0x1e, 0x61, 0xae, 0xb0, 0x90, 0xa8, 0xa3, 0x20, 0x0e, 0x0e, 0x2b,
	0xe6, 0x10, 0xd9, 0xc3, 0xf4, 0xde, 0x94, 0xd1, 0x24, 0x0e, 0x0e, 0x21, 0x33, 0xa3, 0x61, 0x16,
	0xb7, 0x8c, 0x5f, 0xca, 0x68, 0x3a, 0x32, 0x47, 0x44, 0x13, 0xd8, 0x26, 0xc8, 0x35, 0x4a, 0x6f,
	0xe9, 0xa4, 0x41, 0x3c, 0xf5, 0xd2, 0x18, 0xc2, 0x3a, 0xd3, 0x68, 0xdd, 0xd6, 0xe7, 0xcd, 0xa9,
	0xcf, 0x4f, 0x26, 0xc3, 0x85, 0x57, 0x82, 0xd9, 0x0d, 0x3d, 0xc0, 0xce, 0x9b, 0xa8, 0x5e, 0x70,
	0x85, 0xe6, 0x9c, 0xe0, 0x6d, 0xc3, 0xd1, 0x1a, 0x2d, 0x99, 0x43, 0x54, 0xc0, 0xd2, 0x6b, 0x09,
	0x81, 0x30, 0x2b, 0x4b, 0xe9, 0xa2, 0xdb, 0xd9, 0xe8, 0x7e, 0xb0, 0xa9, 0x6f, 0xda, 0x5e, 0x9b,
	0x31, 0x87, 0xc8, 0x0b, 0xcc, 0x94, 0x36, 0x21, 0x4c, 0xfa, 0xdd, 0x79, 0xeb, 0x43, 0x7c, 0x99,
	0x8f, 0x6c, 0xdc, 0x19, 0x43, 0x9e, 0x75, 0x18, 0x85, 0xa3, 0xa1, 0x99, 0xe9, 0x2b, 0x6c, 0x3e,
	0xb1, 0x6d, 0x85, 0xaf, 0xf7, 0x04, 0x0b, 0x89, 0xc3, 0x77, 0xa7, 0x6a, 0xff, 0xcb, 0x24, 0x0e,
	0x57, 0x55, 0xd3, 0x23, 0x6c, 0x1d, 0xd1, 0x55, 0x78, 0x86, 0xa5, 0x44, 0xd5, 0xff, 0xa3, 0x2e,
	0x0c, 0xbe, 0xaa, 0xfa, 0xf8, 0x06, 0xab, 0xbf, 0xe3, 0x04, 0x60, 0x9e, 0xda, 0x72, 0xfb, 0x07,
	0xb2, 0x86, 0x45, 0x5a, 0x55, 0x16, 0x04, 0x64, 0x05, 0xb3, 0xa4, 0x15, 0x0a, 0xf7, 0x93, 0x7c,
	0x6e, 0x5f, 0xf0, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x78, 0x79, 0x5d, 0x51, 0xd1, 0x01, 0x00,
	0x00,
}
