// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	GateRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登录认证 协议号3  重连 5
type GateRequest struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	Uid    uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	ChanId string `protobuf:"bytes,3,opt,name=chanId" json:"chanId,omitempty"`
}

func (m *GateRequest) Reset()                    { *m = GateRequest{} }
func (m *GateRequest) String() string            { return proto.CompactTextString(m) }
func (*GateRequest) ProtoMessage()               {}
func (*GateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GateRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GateRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GateRequest) GetChanId() string {
	if m != nil {
		return m.ChanId
	}
	return ""
}

func init() {
	proto.RegisterType((*GateRequest)(nil), "pb.GateRequest")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2, 0xe7, 0xe2,
	0x76, 0x4f, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x2b,
	0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x04,
	0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x82, 0x40, 0x4c, 0x90, 0xca,
	0xe4, 0x8c, 0xc4, 0x3c, 0xcf, 0x14, 0x09, 0x66, 0x88, 0x4a, 0x08, 0x2f, 0x89, 0x0d, 0x6c, 0xb6,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xbb, 0xa9, 0xa7, 0x6b, 0x00, 0x00, 0x00,
}
