// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	GateRequest
	CenterRequest
	CenterResponse
	HelloRequest
	HelloResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// gate服务 登录认证 协议号3  重连 5
type GateRequest struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	Uid    uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	ChanId string `protobuf:"bytes,3,opt,name=chanId" json:"chanId,omitempty"`
}

func (m *GateRequest) Reset()                    { *m = GateRequest{} }
func (m *GateRequest) String() string            { return proto.CompactTextString(m) }
func (*GateRequest) ProtoMessage()               {}
func (*GateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GateRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GateRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GateRequest) GetChanId() string {
	if m != nil {
		return m.ChanId
	}
	return ""
}

// center服务 rpc接口
type CenterRequest struct {
	Uid []uint64 `protobuf:"varint,1,rep,packed,name=uid" json:"uid,omitempty"`
}

func (m *CenterRequest) Reset()                    { *m = CenterRequest{} }
func (m *CenterRequest) String() string            { return proto.CompactTextString(m) }
func (*CenterRequest) ProtoMessage()               {}
func (*CenterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CenterRequest) GetUid() []uint64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

type CenterResponse struct {
	Online []bool `protobuf:"varint,1,rep,packed,name=online" json:"online,omitempty"`
}

func (m *CenterResponse) Reset()                    { *m = CenterResponse{} }
func (m *CenterResponse) String() string            { return proto.CompactTextString(m) }
func (*CenterResponse) ProtoMessage()               {}
func (*CenterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CenterResponse) GetOnline() []bool {
	if m != nil {
		return m.Online
	}
	return nil
}

// 测试接口请求 1001
type HelloRequest struct {
	ReqMsg string `protobuf:"bytes,1,opt,name=req_msg,json=reqMsg" json:"req_msg,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloRequest) GetReqMsg() string {
	if m != nil {
		return m.ReqMsg
	}
	return ""
}

// 测试接口返回 1002
type HelloResponse struct {
	RespMsg string `protobuf:"bytes,1,opt,name=resp_msg,json=respMsg" json:"resp_msg,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HelloResponse) GetRespMsg() string {
	if m != nil {
		return m.RespMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GateRequest)(nil), "pb.GateRequest")
	proto.RegisterType((*CenterRequest)(nil), "pb.CenterRequest")
	proto.RegisterType((*CenterResponse)(nil), "pb.CenterResponse")
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "pb.HelloResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbf, 0x4e, 0x86, 0x30,
	0x14, 0x47, 0x53, 0x30, 0x80, 0x57, 0x30, 0x86, 0x41, 0x71, 0xc3, 0x2e, 0x12, 0x07, 0x17, 0x1f,
	0xc1, 0x41, 0x1d, 0x88, 0x49, 0x5f, 0xc0, 0xf0, 0xe7, 0x06, 0x49, 0xa0, 0x2d, 0xbd, 0xe5, 0xfd,
	0xbf, 0x14, 0xda, 0xe4, 0xdb, 0x7a, 0x92, 0xf3, 0x3b, 0xe9, 0x85, 0x7c, 0x50, 0xeb, 0xaa, 0xe4,
	0xbb, 0x36, 0xca, 0xaa, 0x32, 0xd2, 0x3d, 0xff, 0x85, 0xbb, 0xaf, 0xce, 0xa2, 0xc0, 0x6d, 0x47,
	0xb2, 0xe5, 0x23, 0x24, 0x84, 0x83, 0x41, 0x5b, 0xb1, 0x9a, 0x35, 0xb7, 0xc2, 0x53, 0xf9, 0x00,
	0xf1, 0x3e, 0x8f, 0x55, 0x54, 0xb3, 0xe6, 0x46, 0xb8, 0xa7, 0x33, 0x87, 0xff, 0x4e, 0xfe, 0x8c,
	0x55, 0x7c, 0x9a, 0x27, 0xf1, 0x17, 0x28, 0x3e, 0x51, 0x5a, 0x34, 0x21, 0xe9, 0xa7, 0xac, 0x8e,
	0xfd, 0x94, 0x37, 0x70, 0x1f, 0x14, 0xd2, 0x4a, 0x12, 0xba, 0x98, 0x92, 0xcb, 0x2c, 0xf1, 0xd0,
	0x32, 0xe1, 0x89, 0xbf, 0x42, 0xfe, 0x8d, 0xcb, 0xa2, 0x42, 0xeb, 0x09, 0x52, 0x83, 0xdb, 0xdf,
	0x4a, 0x53, 0xf8, 0x9f, 0xc1, 0xad, 0xa5, 0x89, 0xbf, 0x41, 0xe1, 0x45, 0x5f, 0x7c, 0x86, 0xcc,
	0x20, 0xe9, 0x2b, 0x35, 0x75, 0xdc, 0xd2, 0xd4, 0x27, 0xc7, 0xf5, 0x1f, 0x97, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x89, 0xa2, 0xf1, 0x0d, 0x01, 0x00, 0x00,
}
